// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "looklook/app/usercenter/cmd/api/internal/handler/user"
	"looklook/app/usercenter/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// ★ nginx auth_request 子请求的端点 (由 nginx 内部调用, 不走 WithJwt)
				// 详见 internal/handler/authCheckHandler.go
				// 注意: nginx auth_request 子请求默认是 GET, 所以这里要 GET+POST 都注册
				Method:  http.MethodGet,
				Path:    "/auth_check",
				Handler: AuthCheckHandler(serverCtx),
			},
			{
				// 同一 handler, 兼容 POST 调用 (比如外部直接 curl)
				Method:  http.MethodPost,
				Path:    "/auth_check",
				Handler: AuthCheckHandler(serverCtx),
			},
		},
		rest.WithPrefix("/usercenter/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/detail",
				Handler: user.DetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/wxMiniAuth",
				Handler: user.WxMiniAuthHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/usercenter/v1"),
	)
}
